[build]
  command = "npm run build"
  publish = "dist"
  Functions = "functions"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

[[redirects]]
    from = "/next"
    to = "/.netlify/functions/next"
    status = 301
    force = true

[[redirects]]
    from = "/prev"
    to = "/.netlify/functions/prev"
    status = 301
    force = true

[[redirects]]
    from = "/random"
    to = "/.netlify/functions/random"
    status = 301
    force = true