[build]
  command = "npm run build"
  publish = "dist/site"
  functions = "dist/functions"

[[redirects]]
  from = "/embed.html"
  to = "/embed"

[[redirects]]
  from = "/next"
  to = "/.netlify/functions/next"
  status = 301
  force = true

[[redirects]]
  from = "/prev"
  to = "/.netlify/functions/prev"
  status = 301
  force = true

[[redirects]]
  from = "/random"
  to = "/.netlify/functions/random"
  status = 301
  force = true
